name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d754f577d59b9074bcdb90a8e99254548554c8fdcdab444d7c37aae4d305f0d8"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
