name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "becf6d79e375dfc17c3c22e1f4a0f813fcedf129ecfadaf9ba620acf0ce76d68"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
