name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bba255d66b8d71ef5f0c67ca3d3398f9c1d0d2592d820290290ed566dbbf413d"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
