name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e206d9d3d53aecceaca16df2c950369fa28a060082b2ebdf245a4b63f1544d40"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
