name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "231bff772e1842815ddaa33d33196a08c86411410c5e6e932171d96bdd8becfc"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
