name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73e6b2189f863b18e29ecd0dbeef7b8b6f363f1591486e9520b1308242ba8f38"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
