name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb7aaff566753a9718c84c22d001879addba4957bb023cb60e90b3a0ae4485ce"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
