name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "585f681312be059bf05e9d2041caf919178b1e78d0e84e260ac11e1a2b25a69d"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
