name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "498d3c3ee11deb95e460a4427c659bdbdb89520fe02d30e76443f49748a05bb1"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
