name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccb9ecb53cecd8e8817598d052785b089e195c32003561f142fd116e8b936116"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
