name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cd28b3b318d7113cd20b283194786a5ff9d648e622ab134c4303f1ec6d32e5b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
