name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77e9b4a076d08f4f2faf1e446bf78c2816e9d768885766fe333291d62ed4e6f8"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
