name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c0782ba7b3a07bb7cf048b447bb3c3fcebfbd67af9f0a5a2b5ded1ecf1f571b"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
