name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14fc969b6ffff730821ae323065679c1b867002fb66f380b477566528c7f47ca"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
