name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6abcf2661cb218c8885a915918176fff93ba07aaac77afd2d964df04908c11d"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
