name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29342819f9738b6ea761456380b7acf65ac0635364811874b4df0dc5b5f61dae"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
