name = "Vinegar Fabricpack Reforged"
author = "VinegarHQ"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9ee67f18b09bb6f9e3b8f3969fe02da7519a80c376e61a5afaf40247b4e8119"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
